create table lost_item (
    id               bigint generated by default as identity primary key,
    item_name        varchar(255)                not null,
    place            varchar(255)                not null,
    quantity         integer                     not null,
    claimed_quantity integer                     not null default 0,
    reported_at      timestamp(6) with time zone not null,
    constraint ck_lost_item_quantity_positive check (quantity > 0),
    -- Last line of defence behind LostItemRepository.tryClaimQuantity: never over-claim.
    constraint ck_lost_item_claimed_within_quantity check (claimed_quantity between 0 and quantity)
);

create table item_claim (
    id           bigint generated by default as identity primary key,
    lost_item_id bigint                      not null,
    user_id      varchar(255)                not null,
    quantity     integer                     not null,
    claimed_at   timestamp(6) with time zone not null,
    constraint fk_item_claim_lost_item foreign key (lost_item_id) references lost_item (id),
    constraint ck_item_claim_quantity_positive check (quantity > 0)
);

-- The admin report loads claims by lost item id.
create index ix_item_claim_lost_item_id on item_claim (lost_item_id);
